services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - "3050:3050"
    volumes:
    - ./backend:/app
    depends_on:
    - db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
     - "5173:5173"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  nginx:
    build:
      context: ./frontend copy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pg_data: